name: evox
base: core18
adopt-info: evox
summary: "EvoX coin: official wallet. Secure. Scalable. Easy to Use."
description: |
  EvoX is a scalable and secure coin, designed for use in e-commerce.
  The technology behind our blockchain provides reliability, security,
  and flexibility a perfect option for P2P transactions.
  More info: http://zano.org
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  evox:
    source: https://github.com/evolution-project/zano.git
    plugin: cmake
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe)"
    configflags:
      - -DBUILD_GUI=TRUE
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/EvoX
      cp $SNAPCRAFT_PART_BUILD/src/EvoX $SNAPCRAFT_PART_INSTALL/opt/EvoX/
      cp $SNAPCRAFT_PART_BUILD/src/simplewallet $SNAPCRAFT_PART_INSTALL/opt/EvoX/
      cp $SNAPCRAFT_PART_BUILD/src/evoxd $SNAPCRAFT_PART_INSTALL/opt/EvoX/
      rsync -a $SNAPCRAFT_PART_SRC/src/gui/qt-daemon/html $SNAPCRAFT_PART_INSTALL/opt/EvoX --exclude less --exclude package.json --exclude gulpfile.js
    build-packages:
      - make
      - g++
      - libboost-all-dev
      - qtwebengine5-dev
      - rsync
    build-attributes: [keep-execstack]
    stage-packages:
      - libboost-system1.65.1
      - libboost-filesystem1.65.1
      - libboost-thread1.65.1
      - libboost-date-time1.65.1
      - libboost-chrono1.65.1
      - libboost-regex1.65.1
      - libboost-serialization1.65.1
      - libboost-program-options1.65.1
      - libboost-locale1.65.1

apps:
  evox:
    command: opt/EvoX/EvoX --data-dir $SNAP_USER_COMMON
    extensions:
      - kde-neon
    plugs:
      - network
      - home
      - desktop
      - opengl #for QML support
      - browser-support #for Qt WebEngine support
      - audio-playback
      - unity7 #for tray icon support
  simplewallet:
    command: opt/EvoX/simplewallet
    plugs:
      - network
      - home
  evoxd:
    command: opt/EvoX/evoxd --data-dir $SNAP_USER_COMMON
    environment:
      LC_ALL: C
    plugs:
      - network
      - network-bind
